#### PvpRealm configuration file ####

pvp-world:
    enable: true
    world: world_pvp
    death-heroes-exp-loss: false
    entry-loc:
        world: world_pvp
        x: 10.0
        y: 64.0
        z: 10.0
        pitch: 0.0
        yaw: 0.0
    default-return-loc:
        world: world
        x: 20.0
        y: 64.0
        z: 20.0
        pitch: 0.0
        yaw: 0.0
    enter-scroll:
        enable: true
        item: 358-50
        consume: true
        delay-sec: 10

pvp-logger:
    enable: true
    enable-op: false
    bypass-friendly: true
    global: true
    message: true
    message-text: ยง4$leaver ยง8left the game during combat with ยง6$playerlist
    heroes-exp-penalty: 0
    kill: false