#### PvpRealm configuration file ####

debug: true
lang: english

pvp-world:
    enable: true
    world: world_pvp
    disable-heroes-death-exp-loss: true
    disable-heroes-mob-exp: true
    disable-weather: true
    entry-loc:
        world: world_pvp
        x: 10.0
        y: 64.0
        z: 10.0
        pitch: 0.0
        yaw: 0.0
    default-return-loc:
        world: world
        x: 20.0
        y: 64.0
        z: 20.0
        pitch: 0.0
        yaw: 0.0
    enter-scroll:
        enable: true
        item: 358-0
        consume: true
        delay-sec: 10
        broadcast-arrival: true

pvp-logger:
    enable: true
    enable-op: false
    bypass-friendly: true
    global: true
    message: true
    heroes-exp-penalty: 0
    kill: false

kit-signs-global: false

death-nodrop-regions:
  - id: pvp_main
    world: world_pvp