name: PvpRealm
main: mccity.plugins.pvprealm.PvpRealm
version: 0.1
author: Galaran

load: POSTWORLD
depend: [Heroes]
softdepend: [Multiverse-Core]

commands:
    pvprealm:
        description: Pvp Realm user command
        permission: pvprealm.command
        permission-message: You do not have permission
        usage: Syntax error! /<command> help for description
        aliases: [pvpr]

permissions:
    pvprealm.command:
        default: op