name: PvpRealm
main: mccity.plugins.pvprealm.PvpRealm
version: 0.5.6
author: Galaran

load: POSTWORLD
depend: [Heroes]
softdepend: [Multiverse-Core, Towny, WorldEdit, WorldGuard]

commands:
    pvprealm:
        description: Pvp Realm user command
        permission: pvprealm.command
        permission-message: You do not have permission
        usage: Syntax error!
        aliases: [pvpr]

permissions:
    pvprealm.command:
        default: op
    pvprealm.kit.placesign:
        default: op
    pvprealm.enterscroll:
        default: op